
# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/irms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器端口配置
server:
  port: 8888
  address: localhost

#Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
